//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorlov.PowerShell.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sorlov.PowerShell.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function global:prompt
        ///{
        ///    $titleString = &quot;{2} [{0}@{1}]&quot; -f [System.Security.Principal.WindowsIdentity]::GetCurrent().Name, [System.Net.Dns]::GetHostName(), $(Get-History -Count 1 | Select -Expand Commandline)
        ///    (Get-Host).UI.RawUI.WindowTitle = $titleString
        ///
        ///	if ($NestedPromptLevel -ge 1)
        ///	{
        ///		Write-Host &quot;[&quot; -NoNewline -ForegroundColor Yellow
        ///		Write-Host $NestedPromptLevel -NoNewline -ForegroundColor White
        ///		Write-Host &quot;]&quot; -NoNewline -ForegroundColor Yellow
        ///	}
        ///
        ///    Write-Host (&quot;$(Get-Loca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Type&gt; 
        ///    &lt;Name&gt;System.Object&lt;/Name&gt; 
        ///    &lt;Members&gt; 
        ///      &lt;ScriptMethod&gt; 
        ///        &lt;Name&gt;MSDN&lt;/Name&gt; 
        ///        &lt;Script&gt; 
        ///	$culture = $host.currentculture 
        ///	if ($args[0]) 
        ///	{ 
        ///	$culture = $args[0] 
        ///	} 
        ///
        ///	if (($global:MSDNViewer -eq $null) -or ($global:MSDNViewer.HWND -eq $null)) 
        ///	{ 
        ///	$global:MSDNViewer = new-object -ComObject InternetExplorer.Application 
        ///	} 
        ///	$Uri = &quot;http://msdn2.microsoft.com/&quot; + $culture + &quot;/library/&quot; +  ($this | select -first 1).GetType().FullName + &quot;.ASPX&quot; 
        ///	$global:M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
    }
}
