//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorlov.PowerShell.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sorlov.PowerShell.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.ComponentModel;
        ///
        ///namespace Sorlov.PowerShell
        ///{
        ///    public static class CrossThread
        ///    {
        ///        public static TResult SafeInvoke&lt;T, TResult&gt;(this T isi, Func&lt;T, TResult&gt; call)
        ///                where T : ISynchronizeInvoke
        ///        {
        ///            if (isi.InvokeRequired)
        ///            {
        ///                IAsyncResult result = isi.BeginInvoke(call, new object[] { isi });
        ///                object endResult = isi.EndInvoke(result);
        ///                return (TResult)endResult;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CrossThread {
            get {
                return ResourceManager.GetString("CrossThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Sorlov.PowerShell.Lib.HTApps;
        ///
        ///namespace Sorlov.PowerShell.SelfHosted.HTApps
        ///{
        ///    static class Program
        ///    {
        ///        [MTAThread]
        ///        static void Main(string[] args)
        ///        {
        ///            System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
        ///            System.Threading.Thread.CurrentThread.CurrentUICulture = System.Globalization.CultureInfo.InvariantCulture;
        ///
        ///            System.Windows.Forms.Application.EnableVisualSty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.IO;
        ///using System.Management.Automation;
        ///using System.Management.Automation.Runspaces;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using System.Threading;
        ///using System.Windows.Forms;
        ///using Sorlov.SelfHostedPS;
        ///using Sorlov.SelfHostedPS.Application;
        ///
        ///namespace Sorlov.PowerShell.Lib.HTApps
        ///{
        ///    public partial class ScriptForm : Form
        ///    {
        ///        public System.Management.Automation.PowerShel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptForm {
            get {
                return ResourceManager.GetString("ScriptForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Sorlov.PowerShell.Lib.HTApps
        ///{
        ///    partial class ScriptForm
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Required designer variable.
        ///        /// &lt;/summary&gt;
        ///        private System.ComponentModel.IContainer components = null;
        ///
        ///        /// &lt;summary&gt;
        ///        /// Clean up any resources being used.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;disposing&quot;&gt;true if managed resources should be disposed; otherwise, false.&lt;/param&gt;
        ///        protected override void Dispose(bool disposing)
        ///        {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptForm_Designer {
            get {
                return ResourceManager.GetString("ScriptForm_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Runtime.InteropServices;
        ///using System.Windows.Forms;
        ///using Sorlov.PowerShell.Lib.HTApps;
        ///
        ///namespace Sorlov.PowerShell.Lib.HTApps
        ///{
        ///     [ComVisible(true)]
        ///    public class ScriptInterface
        ///    {
        ///         private readonly ScriptForm hostForm;
        ///
        ///        public ScriptInterface(ScriptForm hostForm)
        ///        {
        ///            this.hostForm = hostForm;
        ///        }
        ///
        ///         public string InvokeScript(string script)
        ///         {
        ///             return hostForm.SafeInvoke(hFrm=&gt;hFrm.ExecuteScriptOn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptInterface {
            get {
                return ResourceManager.GetString("ScriptInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%
        ///
        ///#
        ///# This block is automatically inserted when using ConvertTo-HTApp
        ///#
        ///# $App is the application context.
        ///# $Document is the htmlDocument context
        ///#
        ///
        ///$App.Title =&quot;$TITLE$&quot;
        ///$App.Width = $WIDTH$
        ///$App.Height = $HEIGHT$
        ///
        ///#
        ///# This is also a good place to define all functions that should be called from
        ///# the JavaScript PSRuntime compability layer.
        ///#
        ///
        ///%&gt;
        ///.
        /// </summary>
        internal static string StandardBlock {
            get {
                return ResourceManager.GetString("StandardBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Sorlov.PowerShell
        ///{
        ///    public static class StringExtension
        ///    {
        ///        public static string Replace(this string originalString, string oldValue, string newValue, StringComparison comparisonType)
        ///        {
        ///            int startIndex = 0;
        ///            while (true)
        ///            {
        ///                startIndex = originalString.IndexOf(oldValue, startIndex, comparisonType);
        ///                if (startIndex == -1)
        ///                    break;
        ///
        ///                originalString = ori [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringExtension {
            get {
                return ResourceManager.GetString("StringExtension", resourceCulture);
            }
        }
    }
}
